spring:
  application:
    name: Hotelowo

  datasource:
    url: jdbc:postgresql://localhost:5432/hotelowo
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false